### ISSUE TITLE
Git sync

### ISSUE THREAD

**Issue by massimosgrelli** [secrez/secrez#122]
it would be useful to have a secret internal command to automatically sync with git if already configured in ~/.secrez directory. Git configuration  is one time and can be done manually, but sync—add, commit and push— is always the same.

**Comment by sullof** [comment]
I will work on it. Thanks

**Comment by sullof** [comment]
I am not sure a command like that is necessary. You can create aliases like
```
alias push -c 'lcd ~/.secrez && bash "git add -A" && bash "git commit -m no-message" && bash "git push origin master"'
```
and 
```
alias pull -c 'lcd ~/.secrez && bash "git pull origin master"
``` 
To push changes to the repo and pull changes from the repo. 

@massimosgrelli, why do you think an internal `git` command would be better?

In the end, from secrez point of view you need only to be aligned. Also because many other commands are not possible from inside Secrez without creating conflicts.  
For example, to replicate an account on a new pc, the repo must be cloned before running Secrez, or a set of incompatible keys will be created making impossible the merge.

**Comment by massimosgrelli** [comment]
Done. You are right and I just added those two alias to my secrez.

**Comment by sullof** [comment]
I found and edge case where it is better if the command is run inside Secrez. Specifically to avoid conflicts if someone is running two secrez at the same time, any variable `tree.previousRootEntry` in any tree should be reset.

**Comment by sullof** [comment]
Solved in https://github.com/secrez/secrez/pull/134
