### ISSUE TITLE
Edit a file with Visual Studio Code is not working

### ISSUE THREAD

**Issue by massimosgrelli** [secrez/secrez#123]
I tried to launch `edit filename -e code` but the file did not showed up in the text editor.

**Comment by sullof** [comment]
It works only with editor that run in the terminal. If not, it is not able to manage the child process.
And, btw, I am not sure that it is safe to use and IDE for that. Actually, even with vim is not that safe because it uses a temporary file. Secrez forces the position of the file and is careful about deleting it as soon as possible, but it would be better to use an editor that manages files purely in memory.
